### ISSUE TITLE
Include player(s) position in combat log

### ISSUE THREAD

**Issue by Niqhtbulb** [SuperNerdEric/combat-logger#2]
Love the plugin! I think it'd be really cool if the player's position was included in the combat log, to further enable analysing one's combat performance. For example in something like Corrupted Gauntlet, the ability to review positioning could help a lot in finding lost ticks. (and it'd enable the possibility of a replay, just like in warcraftlogs)

**Comment by SuperNerdEric** [comment]
Hi,

This is something I'd probably like to add eventually, Though there's a few other things I want to get to first and the Runelite approval process can be kind of slow.

**Comment by Scotho** [comment]
As a fellow wow nerd, I love this idea and the direction of your plugin Eric. it certainly provides a lot of fun programming challenges. If you're interested in contributors, reach out!

**Comment by SuperNerdEric** [comment]
Hi @Scotho ,

I'm happy to take contributions for both the plugin and the website. If you're interested in contributing you can join the discord here.

https://discord.com/invite/ZydwX7AJEd

**Comment by SuperNerdEric** [comment]
Position tracking has been added in https://github.com/SuperNerdEric/combat-logger/commit/14c88c731c9544b49ff37089f84b73009af83a3a, but it won't go live until RuneLite merges https://github.com/runelite/plugin-hub/pull/6903
