### ISSUE TITLE
Missing Burning Claw Special Attack Animation

### ISSUE THREAD

**Issue by RonnyTommy548** [SuperNerdEric/combat-logger#4]
When you do a burning claw special attack, there is no message in the combat log about your player doing an attack animation, unlike other specs/attacks which do have this message.

**Comment by SuperNerdEric** [comment]
Thanks for the report!

I've fixed it in https://github.com/SuperNerdEric/combat-logger/commit/86e75dd3e15ffb4a241f352975b243a8b76d2669, but it won't go live until RuneLite merges https://github.com/runelite/plugin-hub/pull/6903
