### ISSUE TITLE
[Bug] Disabling overlay doesn't remove overlay context from HUD

### ISSUE THREAD

**Issue by TimOosterom** [SuperNerdEric/combat-logger#7]
The right click context menu still appears in the area the overlay was originally at. This only happens with in-game clicks (UI right clicks don't show the context menu).

![image](https://github.com/user-attachments/assets/49ee4e4f-5044-4892-9634-5f04f3811163)
![image](https://github.com/user-attachments/assets/06774680-7aff-4ca7-97c9-166ece2b9748)

**Comment by Scotho** [comment]
Hey Tim, thanks for the report.

We noticed this a few days ago and the fix is just waiting for runelite's approval at https://github.com/runelite/plugin-hub/pull/6931
